### ISSUE TITLE
getSubsetID in ItemsMap and SubsetManager are returning undefined in subsetId

### ISSUE THREAD

**Issue by khenissimehdi** [IFCjs/web-ifc-viewer#164]
Hello i was playing around with the example project and i wanted to create a subset and do some operations on it but so i created a custom subset using for example this code  

Sample code :
```js
var tables = await viewer.IFC.loader.ifcManager.getAllItemsOfType(modeID,IFCFURNISHINGELEMENT);
 const config = {
      modelID: modeID,
      ids: tables,
      customID:"stuff"
  }

var sub = manager.createSubset(config);
var mesh = managr.getSubset(modeID,"DEFULT","stuff");
console.log(mesh);
```
but i got this 
```
main.js:97380 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mesh')
    at SubsetManager.getSubset (main.js:97380:39)
    at IFCManager.getSubset (main.js:100123:29)
    at window.onclick (main.js:121981:23)
```
the methods that cause the problem ( same for both classes ItemsMap and SubsetManager)
```js
      getSubsetID(modelID, material, customID = 'DEFAULT') {
        const baseID = modelID;
        const materialID = material ? material.uuid : 'DEFAULT';
        return `${baseID} - ${materialID} - ${customID}`;
      }
```
How i fixed it ( dirty fix i didn't  want to change the global logic of the code) 
```js
      getSubsetID(modelID, material, customID = 'DEFAULT') {
        const baseID = modelID;
        const materialID = (Object.prototype.toString.call(material) === '[object String]') || !material ? 'DEFAULT' : material.uuid;
        return `${baseID} - ${materialID} - ${customID}`;
      }
```

The problem is with the material param passed to the function getSubset in ItemMap we have undefined and in SubsetManager we can pass anything forexample if we pass a string it will break everything.

**Comment by agviegas** [comment]
Hi, you don't need to use the second parameter to retrieve the subset. Only the customID should suffice

**Comment by khenissimehdi** [comment]
Yes even with the only the custom id i got the same problem

**Comment by agviegas** [comment]
Can you please provide a minimal repository reproducing this issue?

**Comment by khenissimehdi** [comment]
> Yes even with the only the custom id i got the same problem 

I rechecked again to be sure and yes same problem when for example i call. 

´´´js
manager.getSubset(modelID,"stuff")
´´´

**Comment by khenissimehdi** [comment]
> Can you please provide a minimal repository reproducing this issue?

Yes sir

**Comment by khenissimehdi** [comment]
> Can you please provide a minimal repository reproducing this issue?

Hello here is the git repo : https://github.com/khenissimehdi/BimViewerBroken

Here is the part of the test code in main.js 
```js
window.onclick = async () => {
    const result = await viewer.IFC.selector.pickIfcItem(false);
    if (!result) return;
    const { modelID } = result;
    var tables = await viewer.IFC.loader.ifcManager.getAllItemsOfType(modelID,IFCFURNISHINGELEMENT);
    const config = {
      modelID: modelID,
      ids: tables,
      customID:"tables"
    };

  manager.createSubset(config);
  var subset = manager.getSubset(modelID,"tables");
  console.log(subset);
};
```

**Comment by khenissimehdi** [comment]
Hello i just wanted to check in the advancement of this issue

**Comment by agviegas** [comment]
Hi, I have noticed that you have both web-ifc-three and web-ifc-viewer as dependencies. You shouldn't do that, because web-ifc-viewer contains web-ifc-three. You can access the instance of web-ifc-three inside web-ifc-viewer like this: `viewer.IFC.loader`. Can you try removing web-ifc-three as a dependency and using only web-ifc-viewer instead?

**Comment by khenissimehdi** [comment]
Hell sorry for the late reply i tried that but still not working

**Comment by agviegas** [comment]
You are passing the custom ID as the second parameter. You can check out the signature of the getSubset function [here](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#%F0%9F%A7%B1-subsets)

**Comment by khenissimehdi** [comment]
how can i pass only the model Id and the customID only

**Comment by agviegas** [comment]
Passing the other arguments as undefined!
