### ISSUE TITLE
Error when extracting properties (viewer.GLTF.exportIfcFileAsGltf)

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/web-ifc-viewer#212]
I get the following error if I set getProperties: true in the viewer.GLTF.exportIfcFileAsGltf function:

```
web-ifc-api.js:44504  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at 639542469 (web-ifc-api.js:44504:167)
    at IfcAPI2.GetLine (web-ifc-api.js:62076:84)
    at web-ifc-api.js:62164:37
    at Array.forEach (<anonymous>)
    at IfcAPI2.FlattenLine (web-ifc-api.js:62160:23)
    at IfcAPI2.GetLine (web-ifc-api.js:62078:12)
    at web-ifc-api.js:62164:37
    at Array.forEach (<anonymous>)
    at IfcAPI2.FlattenLine (web-ifc-api.js:62160:23)
    at IfcAPI2.GetLine (web-ifc-api.js:62078:12)
```

I've sent the file to ifc.js.contact@gmail.com using swisstransfer.com

**Comment by agviegas** [comment]
Hi, we could take a look, although FYI it is likely that the glTF workflow will be deprecated very soon and substituted by [components](https://github.com/ifcjs/components), which is way faster and consume much less memory. All this will be released with the brand-new documentation covering everything this summer.
