### ISSUE TITLE
 this.wasmModule.OpenModel is not a function

### ISSUE THREAD

**Issue by tptspe** [IFCjs/web-ifc-viewer#239]
Hi team.

When I try to load the ifc file in my gatsby project, it occurs the error.

`Error loading IFC.                              ifc.manager.js 71`
`TypeError: this.wasmModule.OpenModel is not a function
    at IfcAPI2.OpenModel (web-ifc-api.js:61986:1)
    at IFCParser.newIfcModel (IFCLoader.js:152:1)
    at IFCParser.parse (IFCLoader.js:132:1)
    at async IFCManager.parse (IFCLoader.js:2410:1)
    at async Object.eval [as onLoad]                        ifc.manager.js 71`
    

My package versions are like this.    
    "gatsby": "^4.7.0",
    "react": "^17.0.1",
    "web-ifc": "^0.0.42",
    "web-ifc-viewer": "^1.0.218"
    
    
Please help me.

**Comment by agviegas** [comment]
Hi @tptspe 

We are going to officially release the new library [components](https://github.com/ifcjs/components) on September 20. This library will substitute web-ifc-three and web-ifc-viewer. Both WIV and WIT will remain up, but they will be deprecated and won't be maintained any longer.

All our efforts are going towards components now. The API is very similar, so I strongly suggest you make the leap and start using it. You can start using it now (check out the latest alpha version in npm or see the big-restructure branch in the repo. If you still face this issue with it, you can open an issue there and we'll take a look.

Cheers!

**Comment by Braunson** [comment]
Also getting this error, very frustrating after working with the demo for a while only to get to this error with no solution. You should update your docs/examples to mention this.

**Comment by FlorianB-DE** [comment]
Hi @agviegas 

The API is similar?
before I needed 20 lines of code and it worked flawlessly but now I am at roughly 100 lines and I needed to make an account on your website and the buttons don't work, the stacking with pointer events don't work and the whole setup is 100x more complicated:

Please just give me a working example from top to bottom in at most 15 lines where I can add an IFC File via input. Everything more is over the top complicated. 

Best regards,
Florian

**Comment by agviegas** [comment]
Hi @FlorianB-DE,

The API is indeed similar. The reason now it requires more code is because it's more modular/flexible. In programming there's always a tradeoff between abstraction and complexity. You might need more lines, but it can open IFC files orders of magnitude faster, and works for many more use cases. You can find many tutorials in the official documentation. 

Keep in mind that we are working hard to offer all of this for free. If this new library is not useful for your use case, or you think you can make it better, please just make pull requests to improve this, fork any of our repositories and maintain it yourself, or start your own library/community from scratch. 

Otherwise, we'll always be happy to listen to friendly feedback. 🙂
